name: vsflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - rdkit
  - fpdf
  - pdfrw
  - xlsxwriter
  - xlrd
  - pymol-open-source
  - molvs
  - matplotlib
  - coiled
  - dask[complete]
